server:
  port: 9093
  servlet:
    context-path: /

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    druid:
      # wrjweb数据库
      master:
        url: jdbc:mysql://119.23.24.72:3306/db_sperms?useSSL=false&characterEncoding=UTF-8
        username: sperms
        password: Sperms_123
      # 使用druid数据源
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      #慢sql记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

  resources:
      static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/

  mvc:
    throw-exception-if-no-handler-found: true

